### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by 33lucasant** [ramrivera-github/desafio-mercadoliebre#1]
- [ ] 1 - Cumple con este punto. La estructura del sitio contiene todos los elementos.
- [ ] 2 - Cumple con este punto. El contenido del footer está centrado, y además los íconos tienen un tamaño de 2em y un margen inferior de 10px.
- [ ] 3 - No cumple del todo con este punto. El navbar sigue apareciendo en las resoluciones mobile, pero el tamaño de los elementos si cambia, es decir que la página no se rompe.
- [ ] 4 - Cumple con este punto. El sitio cuenta con un formulario de registro.
- [ ] 5 - Cumple con este punto. El sitio cuenta con un formulario de login.
- [ ] 6 - Cumple con este punto. Se muestran mensajes de error cuando hay información errónea en los formularios.
- [ ] 7 - Cumple con este punto. El search bar es un formulario.
- [ ] 8 - Cumple con este punto. Se utilizan transiciones en el sitio.
- [ ] 9 - Creo que la página sigue a la perfección la mayoría de los requerimientos.
- [ ] 10 - Creo que podría mejorar en el apartado estético, como ajustar algunos tamaños, pero no es algo imprescindible.

**Comment by ramrivera-github** [comment]
Corregido los tamaños. Con respecto al navbar, de resolución 361 para abajo no se visualiza.
